services:
  SimplyTestable\WebsiteBundle\Controller\ExceptionController:
    class: SimplyTestable\WebsiteBundle\Controller\ExceptionController
    public: true
    arguments:
      - '%kernel.debug%'
      - '@twig'
      - '@SimplyTestable\WebsiteBundle\Services\NotFoundRedirectService'
      - '@Postmark\PostmarkClient'
      - '@SimplyTestable\WebsiteBundle\Services\TestimonialService'
