services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SimplyTestable\WebsiteBundle\EventListener\CachedResponseEventListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 20 }

  SimplyTestable\WebsiteBundle\EventListener\UserEventListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 25 }
