parameters:
  core_application_urls:
    base: http://null
    jobs_list: /jobs/list/{limit}/{offset}/
  web_client_urls:
    base: http://web.client.simplytestable.com
    start_test: /
    recent_tests: /#recent-tests
    sign_in: /signin/      
    sign_up: /signup/
    start_test_submit: /test/start/
    account: /account/
    test_results: /{website}/{testId}/results/
    test_progress: /{website}/{testId}/progress/    
    plan_subscribe: /account/plan/subscribe/    
    history: /history/    
  not_found_redirect_map:
    /index.php: http://local.simplytestable.com/
    /signup.php: "{{web_client::base}}{{web_client::sign_up}}"
    /signup: "{{web_client::base}}{{web_client::sign_up}}"
    /register.php: "{{web_client::base}}{{web_client::sign_up}}"
  content_type_web_resource_map:
    default: webignition\WebResource\WebResource
    text/html: webignition\WebResource\WebPage\WebPage
    application/xhtml+xml: webignition\WebResource\WebPage\WebPage
    application/json: webignition\WebResource\JsonDocument\JsonDocument    
  plans:
      plan_keys:
        - demo
        - free
        - personal
        - agency
        - business
        - enterprise
      pricing:
        personal: 9
        agency: 19
        business: 59
      pseudo_plans:
        premium: [personal, agency, business]            
      feature_categories:
        test_limitations: "Per-test limitations"
        access_to_results: "Access to results"
        url_discovery: "URL discovery"
        test_types: "Test types"
        advanced_options: "Advanced options"
      feature_properties:
          full_site_tests_per_site:
            name:
              primary: "Full-site test%s"
              secondary: "per site"
            icon: globe
          single_page_tests_per_page:
            name:
              primary: "Single-page test%s"
              secondary: "per page"          
            icon: circle-o
          pages_examined_per_test:
            name:
              primary: "Pages examined"         
              secondary: "per test"
            icon: cogs
          credits_per_month:
            name:
              primary: "Credits per month"         
            icon: star
          private_tests:
            name:
              primary: "Private tests"         
            icon: lock
          results_available_for:
            name:
              primary: "Results available for"         
            icon: clock-o
          read_only_reports:
            name:
              primary: "Read-only reports"         
            icon: eye
          discovery_via_sitemap:
            name:
              primary: "Discovery via sitemap"         
            icon: search
          discovery_via_crawl:
            name:
              primary: "Discovery via crawling"          
            icon: bug
          html_validation:
            name:
              primary: "HTML validation"       
            icon: dot-circle-o
          css_validation:
            name:
              primary: "CSS validation"         
            icon: dot-circle-o
          js_static_analysis:
            name:
              primary: "JS static analysis"         
            icon: dot-circle-o
          link_integrity_checking:
            name:
              primary: "Link integrity checking"          
            icon: dot-circle-o
          https_sites:
            name:
              primary: "HTTPS sites"       
            icon: lock
          http_authentication:
            name:
              primary: "HTTP authentication"           
            icon: lock
          custom_cookies:
            name:
              primary: "Custom cookies"          
            icon: sun-o
      category_to_key_map:
        test_limitations:
          - full_site_tests_per_site
          - single_page_tests_per_page
          - pages_examined_per_test
          - credits_per_month          
        access_to_results:          
          - results_available_for
          - private_tests
          - read_only_reports          
        url_discovery:
          - discovery_via_sitemap
          - discovery_via_crawl          
        test_types:
          - html_validation
          - css_validation
          - js_static_analysis
          - link_integrity_checking          
        advanced_options:
          - https_sites
          - http_authentication
          - custom_cookies        
      features:
        allowed_to_default:
            - full_site_tests_per_site
            - single_page_tests_per_page
            - credits_per_month
            - private_tests
            - read_only_reports
            - discovery_via_sitemap
            - discovery_via_crawl
            - html_validation
            - css_validation
            - js_static_analysis
            - link_integrity_checking
            - https_sites
            - http_authentication
            - custom_cookies  
        defaults:
            full_site_tests_per_site: Unlimited
            single_page_tests_per_page: Unlimited
            credits_per_month: null
            private_tests: false
            read_only_reports: false
            discovery_via_sitemap: true
            discovery_via_crawl: false
            html_validation: true
            css_validation: true
            js_static_analysis: false
            link_integrity_checking: false
            https_sites: false
            http_authentication: false
            custom_cookies: false          
        demo:
            full_site_tests_per_site: 1
            single_page_tests_per_page: 1
            pages_examined_per_test: 10
            results_available_for: "24 hours"
        free:
            pages_examined_per_test: 10
            credits_per_month: 500
            private_tests: true
            results_available_for: "7 days"
            read_only_reports: true
            discovery_via_sitemap: true
            discovery_via_crawl: true
            html_validation: true
            css_validation: true
            js_static_analysis: true
            link_integrity_checking: true
            https_sites: false
            http_authentication: false
            custom_cookies: false
        personal:
            pages_examined_per_test: 50
            credits_per_month: 5000
            private_tests: true
            results_available_for: "Forever"
            read_only_reports: true
            discovery_via_sitemap: true
            discovery_via_crawl: true
            html_validation: true
            css_validation: true
            js_static_analysis: true
            link_integrity_checking: true
            https_sites: true
            http_authentication: true
            custom_cookies: true
        agency:
            pages_examined_per_test: 250
            credits_per_month: 20000
            private_tests: true
            results_available_for: "Forever"
            read_only_reports: true
            discovery_via_sitemap: true
            discovery_via_crawl: true
            html_validation: true
            css_validation: true
            js_static_analysis: true
            link_integrity_checking: true
            https_sites: true
            http_authentication: true
            custom_cookies: true
        business:
            pages_examined_per_test: 2500
            credits_per_month: 100000
            private_tests: true
            results_available_for: "Forever"
            read_only_reports: true
            discovery_via_sitemap: true
            discovery_via_crawl: true
            html_validation: true
            css_validation: true
            js_static_analysis: true
            link_integrity_checking: true
            https_sites: true
            http_authentication: true
            custom_cookies: true      
        enterprise:
            pages_examined_per_test: "10,000+"
            credits_per_month: "100,000+"
            private_tests: true
            results_available_for: "Forever"
            read_only_reports: true
            discovery_via_sitemap: true
            discovery_via_crawl: true
            html_validation: true
            css_validation: true
            js_static_analysis: true
            link_integrity_checking: true
            https_sites: true
            http_authentication: true
            custom_cookies: true     
