homepage:
    pattern:  /
    defaults: { _controller: SimplyTestableWebsiteBundle:Default:index }

roadmap:
    pattern:  /roadmap/
    defaults: { _controller: SimplyTestableWebsiteBundle:Default:roadmap }