homepage:
    pattern:  /
    defaults: { _controller: SimplyTestableWebsiteBundle:Default:index }

roadmap:
    pattern:  /roadmap/
    defaults: { _controller: SimplyTestableWebsiteBundle:Default:roadmap }
    
outdated_browser:
    pattern:  /outdated-browser/
    defaults: { _controller: SimplyTestableWebsiteBundle:Default:outdatedBrowser }    
    
core_application_proxy:
  pattern: /core-application-proxy/
  defaults: { _controller: SimplyTestableWebsiteBundle:CoreApplicationProxy:index }  
  
sign_out_submit:
    pattern:  /signout/
    defaults: { _controller: SimplyTestableWebsiteBundle:User:signOutSubmit }     