imports:
    - { resource: event-listeners.yml }
    - { resource: controllers.yml }

services:
  SimplyTestable\WebsiteBundle\Services\ApplicationConfigurationService:
      arguments:
        - "@=service('kernel').getRootDir()"
        - "@=service('kernel').getCacheDir()"

  SimplyTestable\WebsiteBundle\Services\WebClientRouter:
      arguments:
        - '%web_client_url%'
        - '@SimplyTestable\WebsiteBundle\Services\ResourceLocator'
        - '@SimplyTestable\WebsiteBundle\Services\ApplicationConfigurationService'

  SimplyTestable\WebsiteBundle\Services\NotFoundRedirectService:
      arguments: ['%not_found_redirect_map%', '%base_url%']
      calls:
        - method: addRouter
          arguments:
              - 'local'
              - '@router'
        - method: addRouter
          arguments:
              - 'web_client'
              - '@SimplyTestable\WebsiteBundle\Services\WebClientRouter'

  webignition\SimplyTestableUserSerializer\UserSerializer:
    arguments:
      - '%secret%'

  SimplyTestable\WebsiteBundle\Services\PlansService:
    arguments:
      - '%plans%'
      - '%plan_distinctions%'

  Postmark\PostmarkClient:
    arguments:
      - '%postmark_api_key%'
