services:
  simplytestable.services.httpClient:
    class:  webignition\Http\Client\Client
    
  simplytestable.services.testimonialService:
    class:  SimplyTestable\WebsiteBundle\Services\TestimonialService
    
  simplytestable.services.cachevalidatorheadersservice:
    class:   SimplyTestable\WebsiteBundle\Services\CacheValidatorHeadersService  
    arguments:
        entityManager: "@doctrine.orm.entity_manager"     
        
    
  simplytestable.services.userservice:
    class:  SimplyTestable\WebsiteBundle\Services\UserService        
    arguments:
        session: "@session"
        userSerializerService: "@simplytestable.services.userserializerservice"
        
  simplytestable.services.userserializerservice:
    class:  SimplyTestable\WebsiteBundle\Services\UserSerializerService        
    arguments:
        key: %secret% 
        
  simplytestable.services.notfoundredirectservice:
    class:  SimplyTestable\WebsiteBundle\Services\NotFoundRedirectService   
    arguments:
        web_client_parameters: %web_client% 
        not_found_redirect_map: %not_found_redirect_map%