imports:
#    - { resource: services/commands.yml }
#    - { resource: services/event-listeners.yml }
    - { resource: services/controllers.yml }
#
services:
  SimplyTestable\WebsiteBundle\Services\KernelParametersService: ["@=service('kernel').getRootDir()"]

#  simplytestable.services.testimonialService:
#    class:  SimplyTestable\WebsiteBundle\Services\TestimonialService
#
#  simplytestable.services.cachevalidatorheadersservice:
#    class:   SimplyTestable\WebsiteBundle\Services\CacheValidatorHeadersService
#    arguments:
#        entityManager: "@doctrine.orm.entity_manager"
#
#
#  simplytestable.services.userservice:
#    class:  SimplyTestable\WebsiteBundle\Services\UserService
#    arguments:
#        session: "@session"
#        userSerializerService: "@simplytestable.services.userserializerservice"
#
#  simplytestable.services.userserializerservice:
#    class:  SimplyTestable\WebsiteBundle\Services\UserSerializerService
#    arguments:
#        key: "%secret%"
#
#  simplytestable.services.notfoundredirectservice:
#    class:  SimplyTestable\WebsiteBundle\Services\NotFoundRedirectService
#    arguments:
#        web_client_parameters: "%web_client_urls%"
#        not_found_redirect_map: "%not_found_redirect_map%"
#
#  simplytestable.services.planFeaturesService:
#    class:  SimplyTestable\WebsiteBundle\Services\PlanFeaturesService
#    arguments:
#        planData: "%plans%"
#
#  simplytestable.services.resourcelocator:
#    class:  SimplyTestable\WebsiteBundle\Services\ResourceLocator
#    arguments:
#        kernel: "@kernel"
#
#  simplytestable.services.useragentdetector:
#    class:  SimplyTestable\WebsiteBundle\Services\UserAgentDetector
