parameters:
#    simply_testable_website.example.class: SimplyTestable\WebsiteBundle\Example

services:
#    simply_testable_website.example:
#        class: %simply_testable_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
