imports:
    - { resource: services/event-listeners.yml }
    - { resource: services/controllers.yml }

services:
  SimplyTestable\WebsiteBundle\Services\ApplicationConfigurationService:
      arguments:
        - "@=service('kernel').getRootDir()"
        - "@=service('kernel').getCacheDir()"

  SimplyTestable\WebsiteBundle\Services\WebClientRouter:
      arguments:
        - '%web_client_url%'
        - '@SimplyTestable\WebsiteBundle\Services\ResourceLocator'
        - '@SimplyTestable\WebsiteBundle\Services\ApplicationConfigurationService'

  SimplyTestable\WebsiteBundle\Services\NotFoundRedirectService:
      arguments: ['%not_found_redirect_map%', '%base_url%']
      calls:
        - method: addRouter
          arguments:
              - 'local'
              - '@router'
        - method: addRouter
          arguments:
              - 'web_client'
              - '@SimplyTestable\WebsiteBundle\Services\WebClientRouter'

  SimplyTestable\WebsiteBundle\Services\UserSerializerService:
      arguments: ['%secret%']

  SimplyTestable\WebsiteBundle\Services\PlansService:
    class:  SimplyTestable\WebsiteBundle\Services\PlansService
    arguments:
      - '%plans%'
      - '%plan_distinctions%'
