sudo: false

language: php
php:
  - 7.2

env:
  - SYMFONY_ENV=test

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - cp .travis.composer.config.json ~/.composer/config.json
  - rm phpunit.xml.dist
  - mv phpunit.travis-ci.xml phpunit.xml.dist
  - mv .env.travis-ci .env
  - mysql -e 'CREATE DATABASE myapp_test;'

install:
  - composer install --prefer-dist
  - ./bin/console doctrine:database:create
  - ./bin/console doctrine:migrations:migrate --no-interaction
  - composer config --global process-timeout 2000
  - yarn install

before_script:
  - ./bin/console --env=test cache:clear --no-warmup
  - ./bin/console --env=test cache:warmup

script:
  - yarn lint
  - yarn test
  - yarn run encore production
  - composer ci
