sudo: false

language: php
php:
  - 5.6
  - 7
  - 7.1

before_install:
  - composer self-update
  - cp .travis.composer.config.json ~/.composer/config.json
  - mv app/config/parameters.yml.travis app/config/parameters.yml
  - mv --force app/config/config_travis.yml app/config/config_test.yml
  - cp src/SimplyTestable/WebsiteBundle/Resources/config/parameters.yml.dist src/SimplyTestable/WebsiteBundle/Resources/config/parameters.yml

install:
  - composer install --prefer-dist
  - php bin/console doctrine:database:create
  - php bin/console doctrine:migrations:migrate --no-interaction
  - composer config --global process-timeout 2000
  - yarn install

before_script:
  - php bin/console --env=test cache:clear --no-warmup
  - php bin/console --env=test cache:warmup

script:
  - yarn run stylelint --config .stylelintrc assets/css/
  - yarn run encore production
  - composer ci

matrix:
  allow_failures:
  - php: 7.1
