imports:
    - { resource: parameters/plans.yml }
    - { resource: parameters/plan-distinctions.yml }
    - { resource: parameters/not-found-redirect-map.yml }
    - { resource: parameters.yml }
    - { resource: services.yml }

parameters:
    container.autowiring.strict_mode: true

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
      cookie_domain: .simplytestable.com
      save_path: "%simplytestable_session_savepath%"
    fragments:       ~
    http_method_override: true
    assets:
      json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'

sensio_framework_extra:
    router:
        annotations: false

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: AppBundle:Exception:show

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
