services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    SimplyTestable\WebsiteBundle\Command\:
        resource: '../../src/SimplyTestable/WebsiteBundle/Command'
        autowire: true
        autoconfigure: true
        tags: ['console.command']

    test.webignition\simplytestableuserserializer\userserializer:
      class: webignition\SimplyTestableUserSerializer\UserSerializer
      arguments:
        - '%secret%'

    test.simplytestable\websitebundle\services\testimonialservice:
      class: SimplyTestable\WebsiteBundle\Services\TestimonialService

    test.simplytestable\websitebundle\services\plansservice:
      class: SimplyTestable\WebsiteBundle\Services\PlansService
      arguments:
        - '%plans%'
        - '%plan_distinctions%'

    test.simplytestable\websitebundle\services\notfoundredirectservice:
      class: SimplyTestable\WebsiteBundle\Services\NotFoundRedirectService
      arguments: ['%not_found_redirect_map%', '%base_url%']
      calls:
        - method: addRouter
          arguments:
              - 'local'
              - '@router'
        - method: addRouter
          arguments:
              - 'web_client'
              - '@SimplyTestable\WebsiteBundle\Services\WebClientRouter'

    test.simplytestable\websitebundle\services\applicationconfigurationservice:
      class: SimplyTestable\WebsiteBundle\Services\ApplicationConfigurationService
      arguments:
        - '%kernel.root_dir%'
        - '%kernel.cache_dir%'

    test.simplytestable\websitebundle\services\resourcelocator:
      class: SimplyTestable\WebsiteBundle\Services\ResourceLocator

    test.simplytestable\websitebundle\services\webclientrouter:
      class: SimplyTestable\WebsiteBundle\Services\WebClientRouter
      arguments:
        $baseUrl: '%web_client_url%'

    test.simplytestable\websitebundle\eventlistener\cachedresponseeventlistener:
      class: SimplyTestable\WebsiteBundle\EventListener\CachedResponseEventListener
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 20 }

    test.simplytestable\websitebundle\eventlistener\usereventlistener:
      class: SimplyTestable\WebsiteBundle\EventListener\UserEventListener
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 25 }

    test.simplytestable\websitebundle\services\userservice:
      class: SimplyTestable\WebsiteBundle\Services\UserService
