services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    SimplyTestable\WebsiteBundle\:
        resource: '../../src/SimplyTestable/WebsiteBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/SimplyTestable/WebsiteBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    SimplyTestable\WebsiteBundle\Controller\:
        resource: '../../src/SimplyTestable/WebsiteBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    SimplyTestable\WebsiteBundle\Command\:
        resource: '../../src/SimplyTestable/WebsiteBundle/Command'
        autowire: true
        autoconfigure: true
        tags: ['console.command']

    SimplyTestable\WebsiteBundle\Command\Sitemap\BuildCommand:
      arguments:
        $kernelRootDirectory: '%kernel.root_dir%'
        $webDirectory: '%kernel.project_dir%/web/'

    SimplyTestable\WebsiteBundle\EventListener\CachedResponseEventListener:
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 20 }

    SimplyTestable\WebsiteBundle\EventListener\UserEventListener:
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 25 }

    SimplyTestable\WebsiteBundle\Controller\ExceptionController:
      class: SimplyTestable\WebsiteBundle\Controller\ExceptionController
      public: true
      arguments:
        $debug: '%kernel.debug%'

    SimplyTestable\WebsiteBundle\Services\ApplicationConfigurationService:
        arguments:
          - '%kernel.root_dir%'
          - '%kernel.cache_dir%'

    SimplyTestable\WebsiteBundle\Services\WebClientRouter:
        arguments:
          $baseUrl: '%web_client_url%'

    SimplyTestable\WebsiteBundle\Services\NotFoundRedirectService:
        arguments: ['%not_found_redirect_map%', '%base_url%']
        calls:
          - method: addRouter
            arguments:
                - 'local'
                - '@router'
          - method: addRouter
            arguments:
                - 'web_client'
                - '@SimplyTestable\WebsiteBundle\Services\WebClientRouter'

    webignition\SimplyTestableUserSerializer\UserSerializer:
      arguments:
        - '%secret%'

    SimplyTestable\WebsiteBundle\Services\PlansService:
      arguments:
        - '%plans%'
        - '%plan_distinctions%'

    Postmark\PostmarkClient:
      arguments:
        - '%postmark_api_key%'
