services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\Command\:
        resource: '../../src/AppBundle/Command'
        autowire: true
        autoconfigure: true
        tags: ['console.command']

    AppBundle\Command\Sitemap\BuildCommand:
      arguments:
        $kernelRootDirectory: '%kernel.root_dir%'
        $webDirectory: '%kernel.project_dir%/web/'

    test.webignition\simplytestableuserserializer\userserializer:
      class: webignition\SimplyTestableUserSerializer\UserSerializer
      arguments:
        - '%secret%'

    test.appbundle\services\testimonialservice:
      class: AppBundle\Services\TestimonialService

    test.appbundle\services\plansservice:
      class: AppBundle\Services\PlansService
      arguments:
        - '%plans%'
        - '%plan_distinctions%'

    test.appbundle\services\notfoundredirectservice:
      class: AppBundle\Services\NotFoundRedirectService
      arguments: ['%not_found_redirect_map%', '%base_url%']
      calls:
        - method: addRouter
          arguments:
              - 'local'
              - '@router'
        - method: addRouter
          arguments:
              - 'web_client'
              - '@AppBundle\Services\WebClientRouter'

    test.appbundle\services\webclientrouter:
      class: AppBundle\Services\WebClientRouter
      arguments:
        $baseUrl: '%web_client_url%'
        $kernelRootDirectory: '%kernel.root_dir%'
        $kernelCacheDirectory: '%kernel.cache_dir%'

    test.appbundle\eventlistener\cachedresponseeventlistener:
      class: AppBundle\EventListener\CachedResponseEventListener
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 20 }

    test.appbundle\eventlistener\usereventlistener:
      class: AppBundle\EventListener\UserEventListener
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 25 }

    test.appbundle\services\userservice:
      class: AppBundle\Services\UserService
