services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: true

    SimplyTestable\WebsiteBundle\Command\:
        resource: '../../src/SimplyTestable/WebsiteBundle/Command'
        autowire: true
        autoconfigure: true
        tags: ['console.command']

    SimplyTestable\WebsiteBundle\EventListener\CachedResponseEventListener:
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 20 }

    SimplyTestable\WebsiteBundle\EventListener\UserEventListener:
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 25 }

    SimplyTestable\WebsiteBundle\Services\NotFoundRedirectService:
        arguments: ['%not_found_redirect_map%', '%base_url%']
        calls:
          - method: addRouter
            arguments:
                - 'local'
                - '@router'
          - method: addRouter
            arguments:
                - 'web_client'
                - '@SimplyTestable\WebsiteBundle\Services\WebClientRouter'

    SimplyTestable\WebsiteBundle\Services\ApplicationConfigurationService:
        arguments:
          - "@=service('kernel').getRootDir()"
          - "@=service('kernel').getCacheDir()"

    SimplyTestable\WebsiteBundle\Services\PlansService:
      arguments:
        - '%plans%'
        - '%plan_distinctions%'

    webignition\SimplyTestableUserSerializer\UserSerializer:
      arguments:
        - '%secret%'

    SimplyTestable\WebsiteBundle\Services\WebClientRouter:
        arguments:
          - '%web_client_url%'
          - '@SimplyTestable\WebsiteBundle\Services\ResourceLocator'
          - '@SimplyTestable\WebsiteBundle\Services\ApplicationConfigurationService'

    SimplyTestable\WebsiteBundle\Services\ResourceLocator:

    SimplyTestable\WebsiteBundle\Services\TestimonialService:

    SimplyTestable\WebsiteBundle\Services\UserAgentDetector:

    SimplyTestable\WebsiteBundle\Services\UserService:
