services:
#  simplytestable.command.cachevalidator.clear:
#    class:  SimplyTestable\WebsiteBundle\Command\CacheValidator\ClearCommand
#    arguments:
#        cacheValidatorHeadersService: "@simplytestable.services.cachevalidatorheadersservice"
#    tags:
#      - { name: console.command }

  SimplyTestable\WebsiteBundle\Controller\ExceptionController:
    class: SimplyTestable\WebsiteBundle\Controller\ExceptionController
    public: true
    arguments:
        $debug: '%kernel.debug%'
        $twig: '@twig'
        $notFoundRedirectService: '@SimplyTestable\WebsiteBundle\Services\NotFoundRedirectService'
        $mailer: "@mailer"
        $testimonialService: '@SimplyTestable\WebsiteBundle\Services\TestimonialService'
