services:
  simplytestable.command.cachevalidator.clear:
    class:  SimplyTestable\WebsiteBundle\Command\CacheValidator\ClearCommand
    arguments:
        cacheValidatorHeadersService: "@simplytestable.services.cachevalidatorheadersservice"
    tags:
      - { name: console.command }

  simplytestable.controller.exception:
    class: SimplyTestable\WebsiteBundle\Controller\ExceptionController
    arguments:
        twig: "@twig"
        debug: "%kernel.debug%"
        notFoundRedirectService: "@simplytestable.services.notfoundredirectservice"
        mailer: "@mailer"
        testimonialService: "@simplytestable.services.testimonialservice"
