services:
#  simplytestable.command.cachevalidator.clear:
#    class:  SimplyTestable\WebsiteBundle\Command\CacheValidator\ClearCommand
#    arguments:
#        cacheValidatorHeadersService: "@simplytestable.services.cachevalidatorheadersservice"
#    tags:
#      - { name: console.command }

  SimplyTestable\WebsiteBundle\Controller\ExceptionController:
    class: SimplyTestable\WebsiteBundle\Controller\ExceptionController
    arguments: ['%kernel.debug%']
#        $debug: '%kernel.debug%'
#        notFoundRedirectService: "@simplytestable.services.notfoundredirectservice"
#        mailer: "@mailer"
#        testimonialService: "@simplytestable.services.testimonialservice"
