services:
  simplytestable.controller.exception:
    class: SimplyTestable\WebsiteBundle\Controller\ExceptionController
    arguments:
        twig: "@twig"
        debug: "%kernel.debug%"
        notFoundRedirectService: "@simplytestable.services.notfoundredirectservice"
        mailer: "@mailer"
        testimonialService: "@simplytestable.services.testimonialservice"
