services:
  simplytestable.eventlistener.cachedresponse:
    class: SimplyTestable\WebsiteBundle\EventListener\CachedResponseEventListener
    arguments:
      - '@SimplyTestable\WebsiteBundle\Services\UserService'
      - '@SimplyTestable\WebsiteBundle\Services\CacheValidatorHeadersService'
      - '@logger'
      - '%cacheable_controllers%'
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 25 }
#
#  simplytestable.eventlistener.user:
#    class: SimplyTestable\WebsiteBundle\EventListener\UserEventListener
#    arguments:
#        userService: "@SimplyTestable\WebsiteBundle\Services\UserService"
#    tags:
#      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 20 }
